---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: debug-statements
            language_version: python3
          - id: check-merge-conflict
          - id: check-ast
          - id: check-json
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: detect-private-key
          - id: mixed-line-ending
          - id: pretty-format-json
            args: [--autofix, --indent=4, '--top-keys=_meta,default,develop']


    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            language_version: python3

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.5.1
      hooks:
          - id: mypy
            exclude: ^tests/
            additional_dependencies:
                - pydantic>=2.3.0
            entry: bash -c '{ { mypy --non-interactive --install-types . ;} 2>&1 > /dev/null ; { echo -e "\n" && mypy "$@" ;} > /dev/tty || true ;}' --


    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.289
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
